In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("prev.csv")
data2=pd.read_csv('benchmark.csv')
data2

                  DateTime MixProdElec
0      2019-01-01 00:00:00      Normal
1      2019-01-01 00:30:00      Normal
2      2019-01-01 01:00:00      Normal
3      2019-01-01 01:30:00      Normal
4      2019-01-01 02:00:00      Normal
...                    ...         ...
35035  2021-12-31 21:30:00      Normal
35036  2021-12-31 22:00:00      Normal
35037  2021-12-31 22:30:00      Normal
35038  2021-12-31 23:00:00      Normal
35039  2021-12-31 23:30:00      Normal

[35040 rows x 2 columns]

In [4]:
data

,DateTime,PositionDansAnnee,Annee,Mois,DemiHeure,Jour,JourFerie,JourFerieType,VacancesZoneA,VacancesZoneB,VacancesZoneC,Temperature,Nebulosity,Humidity,WindSpeed,Precipitation
0,2019-01-01 00:00:00,0.000000,2019,janvier,0,mardi,True,1janvier,True,True,True,5.948718,96.000000,87.641026,2.535897,-0.007692
1,2019-01-01 00:30:00,0.000057,2019,janvier,1,mardi,True,1janvier,True,True,True,5.885043,96.230769,87.722222,2.571795,-0.008120
2,2019-01-01 01:00:00,0.000114,2019,janvier,2,mardi,True,1janvier,True,True,True,5.821368,96.461538,87.803419,2.607692,-0.008547
3,2019-01-01 01:30:00,0.000171,2019,janvier,3,mardi,True,1janvier,True,True,True,5.757692,96.692308,87.884615,2.643590,-0.008974
4,2019-01-01 02:00:00,0.000228,2019,janvier,4,mardi,True,1janvier,True,True,True,5.694017,96.923077,87.965812,2.679487,-0.009402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2021-12-31 21:30:00,0.999772,2021,décembre,43,vendredi,False,nonFerie,True,True,True,8.738816,87.303807,90.482456,3.105662,0.039474
35036,2021-12-31 22:00:00,0.999829,2021,décembre,44,vendredi,False,nonFerie,True,True,True,8.694737,87.227661,90.501754,3.079915,0.032632
35037,2021-12-31 22:30:00,0.999886,2021,décembre,45,vendredi,False,nonFerie,True,True,True,8.650658,87.151515,90.521053,3.054167,0.025789
35038,2021-12-31 23:00:00,0.999943,2021,décembre,46,vendredi,False,nonFerie,True,True,True,8.606579,87.075369,90.540351,3.028419,0.018947
35039,2021-12-31 23:30:00,1.000000,2021,décembre,47,vendredi,False,nonFerie,True,True,True,8.562500,86.999223,90.559649,3.002671,0.012105

In [5]:
jrferie=np.array(data['JourFerie'])
jrferie

array([ True,  True,  True, ..., False, False, False])

In [6]:
L=[]
for i in jrferie:
    if i==True:
        L.append('Decarbonne')
    else:
        L.append('Carbonne')
pred=np.array(L)
pred

array(['Decarbonne', 'Decarbonne', 'Decarbonne', ..., 'Carbonne',
       'Carbonne', 'Carbonne'], dtype='<U10')

In [7]:
data

,DateTime,PositionDansAnnee,Annee,Mois,DemiHeure,Jour,JourFerie,JourFerieType,VacancesZoneA,VacancesZoneB,VacancesZoneC,Temperature,Nebulosity,Humidity,WindSpeed,Precipitation
0,2019-01-01 00:00:00,0.000000,2019,janvier,0,mardi,True,1janvier,True,True,True,5.948718,96.000000,87.641026,2.535897,-0.007692
1,2019-01-01 00:30:00,0.000057,2019,janvier,1,mardi,True,1janvier,True,True,True,5.885043,96.230769,87.722222,2.571795,-0.008120
2,2019-01-01 01:00:00,0.000114,2019,janvier,2,mardi,True,1janvier,True,True,True,5.821368,96.461538,87.803419,2.607692,-0.008547
3,2019-01-01 01:30:00,0.000171,2019,janvier,3,mardi,True,1janvier,True,True,True,5.757692,96.692308,87.884615,2.643590,-0.008974
4,2019-01-01 02:00:00,0.000228,2019,janvier,4,mardi,True,1janvier,True,True,True,5.694017,96.923077,87.965812,2.679487,-0.009402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2021-12-31 21:30:00,0.999772,2021,décembre,43,vendredi,False,nonFerie,True,True,True,8.738816,87.303807,90.482456,3.105662,0.039474
35036,2021-12-31 22:00:00,0.999829,2021,décembre,44,vendredi,False,nonFerie,True,True,True,8.694737,87.227661,90.501754,3.079915,0.032632
35037,2021-12-31 22:30:00,0.999886,2021,décembre,45,vendredi,False,nonFerie,True,True,True,8.650658,87.151515,90.521053,3.054167,0.025789
35038,2021-12-31 23:00:00,0.999943,2021,décembre,46,vendredi,False,nonFerie,True,True,True,8.606579,87.075369,90.540351,3.028419,0.018947
35039,2021-12-31 23:30:00,1.000000,2021,décembre,47,vendredi,False,nonFerie,True,True,True,8.562500,86.999223,90.559649,3.002671,0.012105

In [8]:
data['MixProdElec']=pred

In [9]:
data

,DateTime,PositionDansAnnee,Annee,Mois,DemiHeure,Jour,JourFerie,JourFerieType,VacancesZoneA,VacancesZoneB,VacancesZoneC,Temperature,Nebulosity,Humidity,WindSpeed,Precipitation,MixProdElec
0,2019-01-01 00:00:00,0.000000,2019,janvier,0,mardi,True,1janvier,True,True,True,5.948718,96.000000,87.641026,2.535897,-0.007692,Decarbonne
1,2019-01-01 00:30:00,0.000057,2019,janvier,1,mardi,True,1janvier,True,True,True,5.885043,96.230769,87.722222,2.571795,-0.008120,Decarbonne
2,2019-01-01 01:00:00,0.000114,2019,janvier,2,mardi,True,1janvier,True,True,True,5.821368,96.461538,87.803419,2.607692,-0.008547,Decarbonne
3,2019-01-01 01:30:00,0.000171,2019,janvier,3,mardi,True,1janvier,True,True,True,5.757692,96.692308,87.884615,2.643590,-0.008974,Decarbonne
4,2019-01-01 02:00:00,0.000228,2019,janvier,4,mardi,True,1janvier,True,True,True,5.694017,96.923077,87.965812,2.679487,-0.009402,Decarbonne
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35035,2021-12-31 21:30:00,0.999772,2021,décembre,43,vendredi,False,nonFerie,True,True,True,8.738816,87.303807,90.482456,3.105662,0.039474,Carbonne
35036,2021-12-31 22:00:00,0.999829,2021,décembre,44,vendredi,False,nonFerie,True,True,True,8.694737,87.227661,90.501754,3.079915,0.032632,Carbonne
35037,2021-12-31 22:30:00,0.999886,2021,décembre,45,vendredi,False,nonFerie,True,True,True,8.650658,87.151515,90.521053,3.054167,0.025789,Carbonne
35038,2021-12-31 23:00:00,0.999943,2021,décembre,46,vendredi,False,nonFerie,True,True,True,8.606579,87.075369,90.540351,3.028419,0.018947,Carbonne
35039,2021-12-31 23:30:00,1.000000,2021,décembre,47,vendredi,False,nonFerie,True,True,True,8.562500,86.999223,90.559649,3.002671,0.012105,Carbonne

In [12]:
data.to_csv('prédictions')

In [10]:
soumission=data2
soumission['MixProdElec']=pred
soumission

                  DateTime MixProdElec
0      2019-01-01 00:00:00  Decarbonne
1      2019-01-01 00:30:00  Decarbonne
2      2019-01-01 01:00:00  Decarbonne
3      2019-01-01 01:30:00  Decarbonne
4      2019-01-01 02:00:00  Decarbonne
...                    ...         ...
35035  2021-12-31 21:30:00    Carbonne
35036  2021-12-31 22:00:00    Carbonne
35037  2021-12-31 22:30:00    Carbonne
35038  2021-12-31 23:00:00    Carbonne
35039  2021-12-31 23:30:00    Carbonne

[35040 rows x 2 columns]

In [11]:
soumission.to_csv('predictions1.csv',index=False)